# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - ["192.168.20.101:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sunucular"
    static_configs:
      - targets: ['192.168.20.9:9100']
        labels: {'host': 'haproxy1','service': 'loadbalancer'}
      - targets: ['192.168.20.10:9100']
        labels: {'host': 'haproxy2'}
      - targets: ['192.168.20.11:9100']
        labels: {'host': 'web1'}
      - targets: ['192.168.20.12:9100']
        labels: {'host': 'web2'}
      - targets: ['192.168.20.21:9100']
        labels: {'host': 'app1'}
      - targets: ['192.168.20.22:9100']
        labels: {'host': 'app2'}

  - job_name: 'haproxy-exporter'
    static_configs:
    - targets: ['192.168.20.9:8404']
    - targets: ['192.168.20.10:8404']

  - job_name: 'nginx-exporter'
    static_configs:
    - targets: ['192.168.20.11:9113']
    - targets: ['192.168.20.12:9113']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['127.0.0.1:9115']

  - job_name: 'ping'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 8.8.8.8
        - 1.1.1.1
        - 192.168.20.10
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
