# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
  end

  config.vm.define :haproxy1, primary: true do |haproxy1_config|
    haproxy1_config.vm.hostname = 'haproxy1'  
    haproxy1_config.vm.network :private_network, ip: "192.168.20.9"
    haproxy1_config.vm.provision "shell" do |s|
      s.path = "haproxy-setup.sh"
      s.args = "101"
    end
  end

  config.vm.define :haproxy2, primary: true do |haproxy2_config|
    haproxy2_config.vm.hostname = 'haproxy2'
    haproxy2_config.vm.network :private_network, ip: "192.168.20.10"
    haproxy2_config.vm.provision "shell" do |s|
      s.path = "haproxy-setup.sh"
      s.args = "100"
    end
  end

  config.vm.define :web1 do |web1_config|
    web1_config.vm.hostname = 'web1'
    web1_config.vm.network :private_network, ip: "192.168.20.11"
    web1_config.vm.provision :shell, :path => "web-setup.sh"
  end

  config.vm.define :web2 do |web2_config|
    web2_config.vm.hostname = 'web2'
    web2_config.vm.network :private_network, ip: "192.168.20.12"
    web2_config.vm.provision :shell, :path => "web-setup.sh"
  end

  config.vm.define :app1 do |app1_config|
    app1_config.vm.hostname = 'app1'
    app1_config.vm.network :private_network, ip: "192.168.20.21"
    app1_config.vm.provision :shell, :path => "app-setup.sh"
  end

  config.vm.define :app2 do |app2_config|
    app2_config.vm.hostname = 'app2'
    app2_config.vm.network :private_network, ip: "192.168.20.22"
    app2_config.vm.provision :shell, :path => "app-setup.sh"
  end

  config.vm.define :prometheus do |prometheus_config|
    prometheus_config.vm.hostname = 'prometheus'
    prometheus_config.vm.network :private_network, ip: "192.168.20.101"
    prometheus_config.vm.provision :shell, :path => "prometheus-setup.sh"
  end

end
